# Jupyterhub helm chart config

singleuser:
  # Set defaults for resource guarantees and limits
  memory:
    limit: 1G
    guarantee: 1G
  cpu:
    limit: .5
    guarantee: .5
  storage:
    dynamic:
      storageClass: "efs"
  
  # Create different "profiles" which users can sign in to
  profileList:
    - display_name: "Small"
      description: "1GB memory, 0.5 CPU"
      default: true
    - display_name: "Medium"
      description: "2GB memory, 1 CPU"
      # Larger resource guarantees and limits for compute heavy workloads
      kubespawner_override:
        cpu:
          guarantee: 1
          limit: 1
        memory:
          guranatee: 2G
          limit: 2G

hub:
  db:
    pvc:
      storageClassName: "efs"
