# Jupyterhub helm chart config

singleuser:
  # Set defaults for resource guarantees and limits
  storage:
    dynamic:
      storageClass: "efs"
    extraVolumes:
      - name: jupyterhub-shared
        persistentVolumeClaim:
          claimName: jupyterhub-shared-claim
    extraVolumeMounts:
      - name: jupyterhub-shared
        mountPath: /home/jovyan/shared
  memory:
    limit: "512M"
    guarantee: "512M"
  cpu:
    limit: .5
    guarantee: .5

  profileList:
    - display_name: "Extra Small"
      description: "512MB memory, 0.5 CPU"
      default: true
    - display_name: "Small"
      description: "1GB memory, 1 CPU"
      # Larger resource guarantees and limits for compute heavy workloads
      kubespawner_override:
        cpu:
          guarantee: 1
          limit: 1
        memory:
          guarantee: 2G
          limit: 2G

hub:
  db:
    pvc:
      storageClassName: "efs"
