# Jupyterhub helm chart config

singleuser:
  storage:
    dynamic:
      storageClass: "efs"
  profileList:
    - display_name: "X Small"
      description: "512MB memory, 0.5 CPU"
      kubespawner_override:
        memory:
          limit: "512M"
          guarantee: "512M"
        cpu:
          limit: .5
          guarantee: .5
      default: true
    - display_name: "Small"
      description: "1GB memory, 1 CPU"
      kubespawner_override:
        cpu:
          guarantee: 1
          limit: 1
        memory:
          guarantee: 1G
          limit: 1G
hub:
  db:
    pvc:
      storageClassName: "efs"
